CREATE DATABASE `k03`;
USE `03`

CREATE TABLE users(
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(250) NOT NULL,
	`username` VARCHAR(250) NOT NULL UNIQUE,
	`password` VARCHAR(250) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pemasukan1(
`user_id` INTEGER NOT NULL,
`Kode_Pemasukan` INTEGER AUTO_INCREMENT PRIMARY KEY,
`tanggal` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`nominal` INT NOT NULL,
`keterangan` VARCHAR(150) NOT NULL,
FOREIGN KEY(user_id) REFERENCES `users`(id)
);

CREATE TABLE pengeluaran1(
`user_id` INTEGER NOT NULL,
`Kode_Pengeluaran` INTEGER AUTO_INCREMENT PRIMARY KEY,
`tanggal` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`nominal` INT NOT NULL,
`keterangan` VARCHAR(150) NOT NULL,
FOREIGN KEY(user_id) REFERENCES `users`(id)
);